# Generated by Django 2.1.3 on 2018-11-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Microfinance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='state_name',
        ),
    ]
