# Generated by Django 2.1.3 on 2018-12-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Microfinance', '0002_auto_20181129_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='Emp_id',
            new_name='emp_id',
        ),
    ]
